server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: MS-InstantPayment
    static_configs:
      - targets: [localhost]
        labels:
          job: MS-InstantPayment
          __path__: /app/MS-InstantPayment/logs/*.log

  - job_name: MS-Wallet
    static_configs:
      - targets: [localhost]
        labels:
          job: MS-Wallet
          __path__: /app/MS-Wallet/logs/*.log


  - job_name: MS-User
    static_configs:
      - targets: [ localhost ]
        labels:
          job: MS-User
          __path__: /app/MS-User/logs/*.log
