server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: instant-payment-service
    static_configs:
      - targets: [localhost]
        labels:
          job: instant-payment-service
          __path__: /app/instant-payment-service/logs/*.log

  - job_name: wallet-service
    static_configs:
      - targets: [localhost]
        labels:
          job: wallet-service
          __path__: /app/wallet-service/logs/*.log
